import mongoose from "mongoose";

const TitleSchema = new mongoose.Schema({
    viewPort: String,
    type: { type: String, default: 'Title' },
    display: String,
    name: String,
    design: String,// 'Classic' },
    borderBottom: String,// '0' },
    border: String,// '0' },
    beforeBackgroundColor: String,
    afterBackgroundColor: String,
    alignItems: String,//'center' },
    justifyContent: String,// 'space-between' },
    padding: String,// '0' },
    margin: String,
    borderRadius: String,// '0' },
    width: String,
    flexDirection: String,
    title: {
        beforeColor: String,
        afterColor: String,
        //position: String,// 'relative' },
        fontSize: String,//'1.9rem' },
        border: String,// '0' },
        padding: String,// '0' },
        margin: String,
        textBorder: {
            display: String,
            top: String,
            right: String,
            bottom: String,
            left: String,
            height: String,
            width: String,
            borderRadius: String,
            beforeBackgroundColor: String,
            afterBackgroundColor: String,
            transition: String
        }
    },
    strokeLine: {
        display: String,
        top: String,
        right: String,
        bottom: String,
        left: String,
        height: String,
        width: String,
        borderRadius: String,
        backgroundColor: String,
    },
    showAll: {
        display: String,// 'flex' },
        position: String,// 'relative' },
        direction: String,
        padding: String,// '0' },
        margin: String,
        text: {
            fontSize: String,// '1.3rem' },
            beforeColor: String,// '#00000080' },
            afterColor: String,// '#00000080' },
            backgroundColor: String,
            border: String,// '0' },
            text: String,// 'show all' },
        },
        textBorder: {
            display: String,
            top: String,
            right: String,
            bottom: String,
            left: String,
            height: String,
            width: String,
            borderRadius: String,
            beforeBackgroundColor: String,
            afterBackgroundColor: String,
            transition: String
        },
        chevron: {
            display: String,// 'flex' },
            color: String,// 'blue' },
            fontSize: String,// '1.9rem' },
            transform: String,
            transition: String,
        }
    }
})

const btnStyles = {
    btn: String,
    position: String,
    top: String,
    right: String,
    left: String,
    bottom: String,
    fontSize: String,
    height: String,
    width: String,
    margin: String,
    border: String,
    borderRadius: String,
    color: String,
    backgroundColor: String,
    hoverBackgroundColor: String,
}

const addToCartSchema = new mongoose.Schema({
    SlideBoxPort: String,
    type: { type: String, default: 'AddToCart' },
    name: String,
    display: String,
    margin: String,
    padding: String,
    flexDirection: String,
    position: String,
    top: String,
    right: String,
    add: btnStyles,
    delete: btnStyles,
    plus: btnStyles,
    minus: btnStyles,
    num: btnStyles,
})

const MagicBoxSchema = new mongoose.Schema({
    viewPort: String,
    type: { type: String, default: 'MagicBox' },
    name: { type: String, unique: true },
    display: String,//'flex' },
    flexDirection: String,// default: 'column' },
    overlayPadding: String,// '0' },
    backgroundColor: String,
    background: {
        isImage: Boolean,//false },
        title: String,//''
        src: String,//''
    },
    paddingAround: String,//'0' },
    paddingBetween: String,// '0' },
    borderRadius: String,// '0.2rem' },
    height: String,//'fit-content' },
    width: String,// 'fit-content' },
    maxWidth: String,
    minWidth: String,
    position: String,
    top: String,
    right: String,
    bottom: String,
    left: String,
    transition: String,
    beforeTransform: String,
    afterTransform: String,
    beforeBoxShadow: String,
    afterBoxShadow: String,
    zIndex: String,
    canHide: Boolean,
    title: TitleSchema,
    // Timer Bar
    timerBar: {
        display: String,
        position: String,
        height: String,
        width: String,
        top: String,
        right: String,
        bottom: String,
        left: String,
        backgroundColor: String,
        transition: String,
    },
    closeBtn: {
        display: String,
        color: String,
        fontSize: String,
        top: String,
        right: String,
        bottom: String,
        left: String,
    },
    slider: [{
        type: { type: String },// 'Image' },
        display: String,// 'none' },
        height: String,// 'auto' },
        width: String,// 'auto' },
        flexWrap: String,// 'nowrap' },
        border: String,// '0' },
        backgroundColor: String,// 'inherit' },
        paddingAround: String,// '0' },
        paddingBetween: String,// '0' },
        overflow: String,// 'hidden' },
        borderRadius: String,// '0.5rem' },
        canHide: Boolean,
        title: TitleSchema,
        // slide
        slide: [{
            isDefault: Boolean,
            index: Number,
            name: String,
            borderRadius: String,// '0' },
            border: String,// '0' },
            height: String,// 'auto' },
            width: String,// 'auto' },
            backgroundColor: String,// 'inherit' },
            justifyContent: String,// 'flex-start' },
            productVisible: Boolean,
            // slide Title
            title: TitleSchema,
            // image
            image: {
                borderRadius: String,// '0' },
                height: String,// 'auto' },
                width: String,// 'auto' },
                forceWidth: Boolean,//false },
                forceHeight: Boolean,
                animation: Boolean,//true },
            },
        }],
        // product
        product: {
            display: String,// 'flex' },
            addToCart: addToCartSchema,
            justifyContent: String,// 'flex-start' },
            padding: String,// '1rem' },
            name: {
                fontSize: String,// '1.4rem' },
                color: String,// '#444444' },
                hoverColor: String,// 'blue' },
                textAlign: String,// 'center' },
            },
            brand: {
                display: String,// 'flex' },
                fontSize: String,// '1.2rem' },
                color: String,// '#444444' },
                hoverColor: String,// 'blue' },
            },
            priceAndAddToCartWrapper: {
                padding: String,
                flexDirection: String,
                justifyContent: String,
            },
            price: {
                fontSize: String,// '2rem' },
                color: String,// '#444444' },
                hoverColor: String,// 'blue' },
                textAlign: String,// 'center' },
                flexDirection: String,
                padding: String,
                beforeDiscount: {
                    display: String,// 'flex' },
                    fontSize: String,// '1.7rem' },
                    color: String,// '#999999' },
                },
                unit: {
                    display: String,// 'flex' },
                    fontSize: String,// '1.2rem' },
                    color: String,// '#999999' },
                }
            },
            rating: {
                display: String,// 'flex' },
                fontSize: String,// '1.4rem' },
                color: String,// '#444444' },
            },
            reviews: {
                display: String,// 'flex' },
                fontSize: String,// '1.2rem' },
                color: String,// '#444444' },
            },
        },
        // skeleton
        skeleton: {
            fontSize: String,// '1.2rem' },
        },
        // badges
        badges: {
            display: String,// 'grid' },
            top: String,// '0.4rem' },
            left: String,// '0.4rem' },
            borderRadius: String,// '0.5rem' },
            backgroundColors: [String],// ['red', 'orangered', 'orange'] },
            color: String,// '#fff' },
            fontSize: String,// '2rem' },
            badgeWidth: String,// '5rem' },
            badgeHeight: String,// '3.5rem' },
            badges: [String],// [] },
            paddingBetween: String,// '0.5rem' },
        },
        // Timer bar
        timerBar: {
            display: String,
            position: String,
            height: String,
            width: String,
            top: String,
            right: String,
            bottom: String,
            left: String,
            backgroundColor: String,
            transition: String,
        },
        // swiper
        swiper: {
            swipable: Boolean,//true },
            direction: String,// 'X' },
            skip: Number,// 1 },
            skipMore: Number,// 0 },
            chevrons: {
                display: String,// 'none' },
                color: String,// '#fff' },
                height: String,// '8rem' },
                width: String,// '4rem' },
                backgroundColor: String,// '#00000040' },
                hoverBackgroundColor: String,// '#00000060' },
                autoToggle: Boolean,//true },
                boxShadow: Boolean,//true },
            },
            autoPlay: {
                duration: String,// '2000' },
                run: Boolean,//false },
                stopOnHover: Boolean,//false },
            },
            scroll: {
                behavior: String,// 'auto' },
                autoToggle: Boolean,//true },
            },
            bullets: {
                display: String,// 'flex' },
                bottom: String,// '1rem' },
                paddingBetween: String,// '0.8rem' },
                fontSize: String,// '1rem' },
            }
        }
    }]
})

const slideSchema = {
    padding: String,
    margin: String,
    flexDirection: String,
    alignItems: String,
    justifyContent: String,
    border: String,
    borderRadius: String,
    fontSize: String,
    beforeColor: String,
    afterColor: String,
    beforeBackgroundColor: String,
    afterBackgroundColor: String,
    transition: String,
    event: String,
    textBorder: {
        top: String,
        right: String,
        bottom: String,
        left: String,
        height: String,
        width: String,
        borderRadius: String,
        beforeBackgroundColor: String,
        afterBackgroundColor: String,
        beforeTransform: String,
        afterTransform: String,
        transition: String
    },
    icon: {
        display: String,
        beforeColor: String,
        afterColor: String,
        fontSize: String
    },
}

const LiteBoxSchema = new mongoose.Schema({
    active: Boolean,
    type: { type: String, default: 'LiteBox' },
    name: { type: String, unique: true },
    position: String,
    top: String,
    right: String,
    bottom: String,
    left: String,
    flexDirection: String,
    justifyContent: String,
    alignItems: String,
    backgroundColor: String,
    border: String,
    borderRadius: String,
    padding: String,
    maxWidth: String,
    minWidth: String,
    beforeBoxShadow: String,
    afterBoxShadow: String,
    beforeTransform: String,
    afterTransform: String,
    zIndex: String,
    title: slideSchema,
    slide: slideSchema,
    swipable: Boolean,
    transition: String,
    event: String,
    timerBar: {
        backgroundColor: String,
        height: String,
        position: String,
        top: String,
        right: String,
        bottom: String,
        left: String,
        transition: String,
    },
    closeBtn: {
        color: String,
        fontSize: String,
        top: String,
        right: String,
        bottom: String,
        left: String,
    }
})

const AddToCart = mongoose.model("AddToCart", addToCartSchema)
const Title = mongoose.model("Title", TitleSchema)
const MagicBox = mongoose.model("MagicBox", MagicBoxSchema)
const LiteBox = mongoose.model("LiteBox", LiteBoxSchema)

export { Title, MagicBox, AddToCart, LiteBox }

